Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=org.apache.logging.log4j \
       --initialize-at-run-time=org.apache.kafka \
       --initialize-at-run-time=net.jpountz \
       --initialize-at-run-time=org.xerial.snappy \
       --initialize-at-run-time=com.github.luben.zstd \
        --initialize-at-run-time=org.apache.logging.log4j.core.util.internal.UnsafeUtil \
       -Dlog4j2.disableJmx=true \
       --enable-url-protocols=http,https
